name: Build
env:
  JAVA_OPTS: "-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.4

      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Gradle and build jar
        uses: gradle/gradle-build-action@v2
        with:
          arguments: fatJar --no-daemon
        env:
          JAVA_OPTS: ${{ env.JAVA_OPTS }}
